### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by Rahulbaran** [Barissa-Imran/react-gpt3#1]
Hey Imran, We can furture improve your site performance by following these steps:-

1. Using `Webp` image format instead of `png`, which will reduce sizes of your images(There is also `AVIF` format which has support of around 80% in browser, you can see [here](https://caniuse.com/?search=avif))
2. Using `loading="lazy"` attribute in `img` tag.
3. Provide explicit `width` & `height` to images for avoiding **Commulative Layout Shifting**, If you have no idea about it then you can read through [here](https://web.dev/cls/).
4. You can go one step furture and use **image CDN** which will significantly improve site performance. You can look for [imagekit](https://imagekit.io/), which I am using from sometimes.

These are my recommendation for performance improvement.

**Comment by Barissa-Imran** [comment]
This looks good. You can have a go at it

**Comment by Rahulbaran** [comment]
Great, I will try.
